-- ============================================================
-- FILE:    purchase_schema.sql
-- DESC:    Production-grade schema for EleVora Card Store:
--            Phase 4 — Purchase System + User Card Deck
--
-- Tables:
--   1. ALTER bundles          → adds show_cards_in_store flag
--   2. store_products         → RevenueCat product ID mapping
--   3. user_purchases         → Immutable payment ledger
--   4. user_card_deck         → Personal card ownership per user
--
-- Also includes:
--   - Performance indexes on every hot query path
--   - RLS (Row Level Security) policies for Supabase
--   - DB-level CHECK constraints for data integrity
--   - Trigger: auto-expire cards when a room ends
--   - Full column-level comments for developer reference
--
-- Run in Supabase SQL Editor (once, idempotent — safe to re-run)
-- ============================================================


-- ============================================================
-- SECTION 0: Extend Existing bundles Table
-- Add the feature flag that controls card visibility in store.
-- Admin can enable per-bundle when the client is ready.
-- Default FALSE = cards hidden from store (current behaviour).
-- ============================================================

ALTER TABLE public.bundles
  ADD COLUMN IF NOT EXISTS show_cards_in_store BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN public.bundles.show_cards_in_store
  IS 'Future flag. When TRUE the store API includes the full card preview list '
     'for this bundle. Default FALSE hides all cards from the store detail screen. '
     'Admin can enable per-bundle via PUT /admin/bundles/:id.';


-- ============================================================
-- SECTION 1: store_products
--
-- Purpose:
--   Maps Apple App Store / Google Play product identifiers
--   to EleVora bundle plans.
--
-- How it is populated:
--   Auto-generated when admin creates a bundle plan.
--   Two rows inserted per plan (one for ios, one for android).
--   Admin never needs to touch this table manually.
--
-- The store_product_id format (auto-generated by backend):
--   "elevora.{bundle_name_slug}.{plan_name_slug}"
--   Example: "elevora.romantic_pack.starter"
--
-- Admin copies this ID into Apple App Store Connect and
-- Google Play Console when registering the in-app product.
--
-- RevenueCat webhook fires with this ID → backend looks it up
-- here → gets plan_id → knows card_count + bundle → allocates.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.store_products (
  id               UUID    DEFAULT gen_random_uuid() PRIMARY KEY,

  -- FK to the bundle plan this product belongs to
  plan_id          UUID    NOT NULL
                           REFERENCES public.bundle_plans(id)
                           ON DELETE CASCADE,

  -- 'ios' or 'android' — one row per platform per plan
  platform         TEXT    NOT NULL
                           CHECK (platform IN ('ios', 'android')),

  -- The exact product identifier string used in App Store / Play Store
  -- Format: "elevora.{bundle_slug}.{plan_slug}"
  store_product_id TEXT    NOT NULL,

  -- Admin can disable a product mapping without deleting it
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,

  created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

  -- Same product ID cannot exist for the same platform twice
  CONSTRAINT uq_store_product_platform UNIQUE (store_product_id, platform)
);

-- Index for the webhook lookup (most frequent query on this table)
CREATE INDEX IF NOT EXISTS idx_store_products_lookup
  ON public.store_products(store_product_id, platform)
  WHERE is_active = TRUE;

-- Full-table scan for admin list view
CREATE INDEX IF NOT EXISTS idx_store_products_plan
  ON public.store_products(plan_id);

COMMENT ON TABLE  public.store_products                IS 'Auto-populated mapping of Apple/Google IAP product IDs to EleVora bundle plans.';
COMMENT ON COLUMN public.store_products.plan_id        IS 'FK → bundle_plans. Cascade-deleted if the plan is hard-deleted.';
COMMENT ON COLUMN public.store_products.platform       IS 'ios | android. One row per platform per plan.';
COMMENT ON COLUMN public.store_products.store_product_id IS 'Exact product identifier string registered in App Store Connect / Play Console.';
COMMENT ON COLUMN public.store_products.is_active      IS 'Set FALSE to disable a product mapping without deleting it.';


-- ============================================================
-- SECTION 2: user_purchases
--
-- Purpose:
--   Immutable ledger of every successful IAP transaction.
--   This is the financial source of truth — never deleted.
--
-- Key design decisions:
--   - UNIQUE (transaction_id): prevents double card allocation
--     even if RevenueCat fires the same webhook twice.
--   - status starts as 'pending' → moves to 'completed' only
--     after cards are successfully written to user_card_deck.
--   - 'refunded' status triggers automatic card revocation.
--   - Manual grants (admin giving free cards) are also stored
--     here with amount_paid = 0.00 and source = 'manual_grant'.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.user_purchases (
  id               UUID    DEFAULT gen_random_uuid() PRIMARY KEY,

  -- The user who made the purchase
  user_id          UUID    NOT NULL
                           REFERENCES auth.users(id)
                           ON DELETE CASCADE,

  -- Which bundle and which plan was purchased
  bundle_id        UUID    NOT NULL
                           REFERENCES public.bundles(id),
  plan_id          UUID    NOT NULL
                           REFERENCES public.bundle_plans(id),

  -- ── Payment Details ───────────────────────────────────────
  -- Unique ID from RevenueCat / App Store / Play Store
  -- "MANUAL_GRANT_{uuid}" for admin-granted cards (free)
  transaction_id   TEXT    NOT NULL,

  -- Origin of this purchase
  platform         TEXT    NOT NULL
                           CHECK (platform IN ('ios', 'android', 'manual_grant')),

  -- The product identifier string used in the store
  -- Empty string for manual grants
  store_product_id TEXT    NOT NULL DEFAULT '',

  -- Financial fields — NUMERIC(10,2) avoids floating-point errors
  amount_paid      NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  currency         CHAR(3)        NOT NULL DEFAULT 'INR',

  -- Actual number of cards that were allocated (result of 80/20 algo)
  -- May differ from plan card_count in edge cases
  cards_received   INT     NOT NULL DEFAULT 0,

  -- ── Status Lifecycle ──────────────────────────────────────
  -- pending    → being processed (webhook received, cards not yet written)
  -- completed  → cards successfully written to user_card_deck
  -- refunded   → admin processed refund; cards revoked automatically
  -- failed     → webhook received but card allocation failed (retry-safe)
  status           TEXT    NOT NULL DEFAULT 'pending'
                           CHECK (status IN ('pending', 'completed',
                                             'refunded', 'failed')),

  -- Optional admin note (reason for manual grant or refund)
  admin_note       TEXT,

  purchased_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  completed_at     TIMESTAMP WITH TIME ZONE,
  refunded_at      TIMESTAMP WITH TIME ZONE,

  -- Core idempotency guard: same transaction can never be processed twice
  CONSTRAINT uq_transaction_id UNIQUE (transaction_id)
);

-- Fast lookup by user (purchase history screen)
CREATE INDEX IF NOT EXISTS idx_user_purchases_user
  ON public.user_purchases(user_id, purchased_at DESC);

-- Admin filters by status
CREATE INDEX IF NOT EXISTS idx_user_purchases_status
  ON public.user_purchases(status);

-- Admin filters by bundle
CREATE INDEX IF NOT EXISTS idx_user_purchases_bundle
  ON public.user_purchases(bundle_id);

-- Admin filters by platform
CREATE INDEX IF NOT EXISTS idx_user_purchases_platform
  ON public.user_purchases(platform);

-- Revenue analytics: date-range queries
CREATE INDEX IF NOT EXISTS idx_user_purchases_date
  ON public.user_purchases(purchased_at DESC)
  WHERE status = 'completed';

COMMENT ON TABLE  public.user_purchases                IS 'Immutable payment ledger. Source of truth for all IAP transactions and manual card grants.';
COMMENT ON COLUMN public.user_purchases.transaction_id IS 'RevenueCat transaction ID or "MANUAL_GRANT_{uuid}" for admin grants. UNIQUE — prevents double allocation.';
COMMENT ON COLUMN public.user_purchases.platform       IS 'ios | android | manual_grant. manual_grant = admin gave free cards.';
COMMENT ON COLUMN public.user_purchases.cards_received IS 'Actual cards allocated after the 80/20 algorithm ran. May be less than plan card_count in rare edge cases.';
COMMENT ON COLUMN public.user_purchases.status         IS 'pending→completed on success. refunded→triggers card revocation. failed→safe to retry.';
COMMENT ON COLUMN public.user_purchases.admin_note     IS 'Free-text reason for manual grants or refunds. Visible in admin panel.';


-- ============================================================
-- SECTION 3: user_card_deck
--
-- Purpose:
--   Stores every card owned by every user.
--   Each row = one user owns one specific card (instance).
--
-- Card lifecycle:
--   acquired   → is_used=F, expired=F, is_visible=T  (usable)
--   played     → is_used=T, room_id=set               (in-room)
--   room ends  → expired=T, is_visible=F              (hidden)
--
-- Key design decisions:
--   - card_id references the shared cards table (no data copy).
--     Two users can both "own" card C45 — each has their own row.
--   - UNIQUE (purchase_id, card_id): one purchase never gives
--     the same card twice (DB-enforced, not just app-enforced).
--   - is_visible is future-ready: default TRUE now.
--     When client confirms "hide used cards" → one column change.
--   - expired flag + partial index makes the "available cards"
--     query extremely fast even with millions of rows.
--   - room_id SET NULL on room delete → card becomes orphaned
--     but data is preserved (important for support/audit).
-- ============================================================

CREATE TABLE IF NOT EXISTS public.user_card_deck (
  id           UUID    DEFAULT gen_random_uuid() PRIMARY KEY,

  -- Owner of this card instance
  user_id      UUID    NOT NULL
                       REFERENCES auth.users(id)
                       ON DELETE CASCADE,

  -- Which card template this is (points to shared catalog)
  -- Does NOT copy card data — just references it
  card_id      UUID    NOT NULL
                       REFERENCES public.cards(id)
                       ON DELETE CASCADE,

  -- Which purchase gave this card (traceability)
  purchase_id  UUID    NOT NULL
                       REFERENCES public.user_purchases(id)
                       ON DELETE CASCADE,

  -- Which bundle this card came from (for the 80/20 algorithm history)
  bundle_id    UUID    NOT NULL
                       REFERENCES public.bundles(id),

  -- ── Lifecycle Flags ───────────────────────────────────────
  -- Has the user played this card in a room?
  is_used      BOOLEAN NOT NULL DEFAULT FALSE,

  -- Should this card appear in the user's deck view?
  -- TRUE now (cards visible after use — greyed out on frontend).
  -- Future: set FALSE on use to hide card completely.
  is_visible   BOOLEAN NOT NULL DEFAULT TRUE,

  -- Has this card's room session ended?
  -- Set TRUE automatically by trigger when room status → done/expired.
  expired      BOOLEAN NOT NULL DEFAULT FALSE,

  -- ── Usage Tracking ────────────────────────────────────────
  -- Which room was this card played in?
  -- NULL until the card is played.
  room_id      UUID    REFERENCES public.rooms(id)
                       ON DELETE SET NULL,

  used_at      TIMESTAMP WITH TIME ZONE,
  acquired_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

  -- ── Integrity Constraints ─────────────────────────────────
  -- Same purchase cannot give the same card twice
  CONSTRAINT uq_card_per_purchase UNIQUE (purchase_id, card_id)
);

-- ── Indexes ──────────────────────────────────────────────────

-- Primary deck view: all visible cards for a user (most common query)
CREATE INDEX IF NOT EXISTS idx_deck_user_visible
  ON public.user_card_deck(user_id, acquired_at DESC)
  WHERE is_visible = TRUE;

-- Available cards for room: unused + not expired (hot query before room start)
CREATE INDEX IF NOT EXISTS idx_deck_available
  ON public.user_card_deck(user_id)
  WHERE is_used = FALSE AND expired = FALSE AND is_visible = TRUE;

-- Room expiry trigger lookup: all cards used in a specific room
CREATE INDEX IF NOT EXISTS idx_deck_room
  ON public.user_card_deck(room_id)
  WHERE room_id IS NOT NULL;

-- Bundle history for 80/20 algorithm: cards user ever got from a bundle
CREATE INDEX IF NOT EXISTS idx_deck_user_bundle
  ON public.user_card_deck(user_id, bundle_id);

-- Admin audit: all cards for a specific purchase
CREATE INDEX IF NOT EXISTS idx_deck_purchase
  ON public.user_card_deck(purchase_id);

COMMENT ON TABLE  public.user_card_deck              IS 'Personal card ownership. Each row = one user owns one card instance. Card data lives in cards table — this just tracks ownership + lifecycle.';
COMMENT ON COLUMN public.user_card_deck.card_id      IS 'FK → cards. Points to shared card catalog. Does NOT copy card data. Two users can both own card C45.';
COMMENT ON COLUMN public.user_card_deck.purchase_id  IS 'FK → user_purchases. Full traceability: every owned card traces back to a specific payment.';
COMMENT ON COLUMN public.user_card_deck.bundle_id    IS 'FK → bundles. Used by the 80/20 algorithm to know which cards the user already received from this bundle.';
COMMENT ON COLUMN public.user_card_deck.is_used      IS 'TRUE after user plays this card in a room. Used by frontend to grey out played cards.';
COMMENT ON COLUMN public.user_card_deck.is_visible   IS 'Controls deck display. TRUE = show. Future: set FALSE on use to fully hide expired cards.';
COMMENT ON COLUMN public.user_card_deck.expired      IS 'TRUE after the room session ends. Set automatically by trigger on room completion.';
COMMENT ON COLUMN public.user_card_deck.room_id      IS 'The room this card was played in. NULL until played. SET NULL if room is hard-deleted.';


-- ============================================================
-- SECTION 4: Trigger — Auto-Expire Cards When Room Ends
--
-- When a room's status changes to 'completed' or 'expired',
-- all cards that were played IN that room are automatically
-- set to: expired=TRUE, is_visible=FALSE.
--
-- This runs at the DB level — zero application code required.
-- Even if the backend crashes mid-game, this trigger fires
-- when the room status is updated (by any code path).
-- ============================================================

CREATE OR REPLACE FUNCTION public.fn_expire_room_cards()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  -- Only fire when status changes TO a terminal state
  IF NEW.status IN ('completed', 'expired')
     AND OLD.status NOT IN ('completed', 'expired') THEN

    UPDATE public.user_card_deck
    SET
      expired    = TRUE,
      is_visible = FALSE,
      used_at    = COALESCE(used_at, NOW())
    WHERE
      room_id  = NEW.id
      AND is_used = TRUE
      AND expired = FALSE;

  END IF;
  RETURN NEW;
END;
$$;

-- Attach trigger to rooms table
DROP TRIGGER IF EXISTS trg_expire_room_cards ON public.rooms;

CREATE TRIGGER trg_expire_room_cards
  AFTER UPDATE OF status ON public.rooms
  FOR EACH ROW
  EXECUTE FUNCTION public.fn_expire_room_cards();

COMMENT ON FUNCTION public.fn_expire_room_cards()
  IS 'Auto-expires all used cards in a room when room status → completed/expired. '
     'Fires at DB level — independent of application code.';


-- ============================================================
-- SECTION 5: Row Level Security (RLS)
--
-- Supabase uses RLS to enforce data access at the DB level.
-- These policies ensure:
--   - Users can only see/modify their own cards and purchases.
--   - Admin bypasses RLS via service_role key.
--   - RevenueCat webhook uses service_role (no RLS restriction).
-- ============================================================

-- ── store_products ──────────────────────────────────────────
ALTER TABLE public.store_products ENABLE ROW LEVEL SECURITY;

-- Public can read active products (needed for store display)
CREATE POLICY "store_products_public_read"
  ON public.store_products FOR SELECT
  USING (is_active = TRUE);

-- ── user_purchases ──────────────────────────────────────────
ALTER TABLE public.user_purchases ENABLE ROW LEVEL SECURITY;

-- Users can only see their own purchases
CREATE POLICY "user_purchases_owner_read"
  ON public.user_purchases FOR SELECT
  USING (auth.uid() = user_id);

-- Only service_role (webhook/backend) can insert purchases
CREATE POLICY "user_purchases_service_insert"
  ON public.user_purchases FOR INSERT
  WITH CHECK (TRUE);  -- backend uses service_role key, bypasses RLS

-- ── user_card_deck ──────────────────────────────────────────
ALTER TABLE public.user_card_deck ENABLE ROW LEVEL SECURITY;

-- Users can only see their own cards
CREATE POLICY "deck_owner_read"
  ON public.user_card_deck FOR SELECT
  USING (auth.uid() = user_id);

-- Users can update their own cards (play a card → is_used=TRUE)
CREATE POLICY "deck_owner_update"
  ON public.user_card_deck FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Only backend (service_role) can insert card deck rows
CREATE POLICY "deck_service_insert"
  ON public.user_card_deck FOR INSERT
  WITH CHECK (TRUE);


-- ============================================================
-- SECTION 6: Helpful DB View — v_user_deck_detail
--
-- Pre-joins user_card_deck with the cards catalog + categories.
-- Used by GET /user/deck to avoid multiple round-trips.
-- ============================================================

CREATE OR REPLACE VIEW public.v_user_deck_detail AS
SELECT
  ucd.id              AS deck_card_id,
  ucd.user_id,
  ucd.purchase_id,
  ucd.bundle_id,
  ucd.is_used,
  ucd.is_visible,
  ucd.expired,
  ucd.room_id,
  ucd.used_at,
  ucd.acquired_at,

  -- Card details (from shared catalog)
  c.id                AS card_id,
  c.name              AS card_name,
  c.card_type,
  c.power_description,
  c.image_url,

  -- Category details
  cat.id              AS category_id,
  cat.name            AS category_name,
  cat.theme_color

FROM public.user_card_deck   ucd
JOIN public.cards             c   ON c.id  = ucd.card_id
LEFT JOIN public.card_categories cat ON cat.id = c.category_id;

COMMENT ON VIEW public.v_user_deck_detail
  IS 'Flattened view of user_card_deck joined with card and category details. '
     'Used by GET /user/deck and GET /user/deck/available to avoid N+1 queries.';
